// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $history from "./routes/history.tsx";
import * as $index from "./routes/index.tsx";
import * as $DailyTracker from "./islands/DailyTracker.tsx";
import * as $HistoryView from "./islands/HistoryView.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/history.tsx": $history,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DailyTracker.tsx": $DailyTracker,
    "./islands/HistoryView.tsx": $HistoryView,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
